[package]
name = "webshakerRUSTEdition"
version = "0.1.0"
edition = "2024"

[dependencies]
rdev = "0.5.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serialport = "4.8.1"
thiserror = "2.0.17"
